# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessorApp', '0001_squashed_0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
