# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessorApp', '0002_task_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(default=0, upload_to='uploaded-images'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(editable=False),
        ),
    ]
