# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-14 22:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessorApp', '0003_auto_20151214_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_change',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2015, 12, 14, 22, 56, 56, 186014, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
