# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessorApp', '0004_auto_20151214_2256'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='image_converted',
            field=models.ImageField(default=None, upload_to=b''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to=b''),
        ),
    ]
