# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-16 02:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ImageProcessorApp', '0005_auto_20151215_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.IntegerField(choices=[(1, 'uploaded'), (2, 'processing...'), (3, 'finished')], default=1),
        ),
    ]
